# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0bf9e471c1bc29befb2ed3b228cbdeec4f1a6786fac2e2639fe26ba483493f36278cc824d849342403a8371770b2c110046049d22380b895e52f0acbf3331f7

test:
  secret_key_base: 983272ea275c897d029877987fb089d2303a0306ad76200b2a5da1703d286aacd125a6db9bf05f2451ea786f14dd859eace39051b3d8fd5185940470ee9f0aba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
